version: '3.8'

services:

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/mailingApi
      - SENDING_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTA0NzAyNTYsImlzcyI6ImZhYnJpcXVlIiwibmFtZSI6ImFsZXhleTI3MDcyMiJ9.Ahu4tWiGYNLruqrRceJ1pDnDe25Rm_dr6AS0KDmf7eo
      - SENDING_API_URL=https://probe.fbrq.cloud/v1
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mailingApi
