"""logs_messages_fix

Revision ID: 3d5dc7e1a772
Revises: f80c1a95e26d
Create Date: 2022-08-01 08:04:13.000612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3d5dc7e1a772'
down_revision = 'f80c1a95e26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.add_column('logs_clients', sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_logs_clients_id'), 'logs_clients', ['id'], unique=False)
    op.drop_column('logs_clients', 'message')
    op.add_column('logs_mailings', sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_logs_mailings_id'), 'logs_mailings', ['id'], unique=False)
    op.drop_column('logs_mailings', 'message')
    op.add_column('logs_messages', sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_logs_messages_id'), 'logs_messages', ['id'], unique=False)
    op.create_index(op.f('ix_mailings_id'), 'mailings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailings_id'), table_name='mailings')
    op.drop_index(op.f('ix_logs_messages_id'), table_name='logs_messages')
    op.drop_column('logs_messages', 'message_text')
    op.add_column('logs_mailings', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_logs_mailings_id'), table_name='logs_mailings')
    op.drop_column('logs_mailings', 'message_text')
    op.add_column('logs_clients', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_logs_clients_id'), table_name='logs_clients')
    op.drop_column('logs_clients', 'message_text')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    # ### end Alembic commands ###
